_target_: src.pointcloud_encoder.uni3d.Uni3D
vision_model_name: eva02_small_patch14_224
pc_feat_dim: 384
pretrained_model_path: pretrained/uni3d/model-s.pt

group_size: 64
num_group: 512
pc_encoder_dim: 512
patch_dropout: 0.0
single_output_token: False

trans2embed: False
embed_dim: 1024