defaults:
  - normalizer: base

_target_: src.dataset.HOI4D.HOI4DDataset

data_dir: data/HOI4D/
cache_dir: data_preprocess/HOI4D/

chunk_size: 30
pointcloud_size: 10000
state_horizon: 1
pcd_horizon: 1
sample_stride: 2 # 30fps -> 15fps

cache_data: true
use_cached_metadata: true

hands:
  - Inspire
  - Leap
  - Wuji
  - Ability
  - Shadow
  - Oymotion
  - Xhand
  - Allegro