defaults:
  - normalizer: full

_target_: src.dataset.Taco.TacoDataset

data_dir: data/Taco/
cache_dir: data_preprocess/Taco/

chunk_size: 30
pointcloud_size: 10000
state_horizon: 1
pcd_horizon: 1
sample_stride: 2 # 30fps -> 15fps

cache_data: true
use_cached_metadata: true

hands:
  - Inspire
  - Leap
  - Wuji
  - Ability
  - Shadow
  - Oymotion
  - Xhand
  - Allegro